"""empty message

Revision ID: 3a77c5e9ed37
Revises: be76263af8d4
Create Date: 2024-05-27 15:11:13.658736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a77c5e9ed37'
down_revision = 'be76263af8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
