"""empty message

Revision ID: 3ed2a4f0bc89
Revises: 7e566bd65033
Create Date: 2024-05-09 19:29:48.468728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ed2a4f0bc89'
down_revision = '7e566bd65033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', sa.String(length=100), nullable=False))
        batch_op.drop_column('captha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captha', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###
